name: Nightly MAPDL check

on:
  workflow_dispatch:
  schedule:  # UTC at 0400
    - cron:  '0 4 * * *'

env:
  PYMAPDL_PORT: 21000  # default won't work on azure
  PYMAPDL_START_INSTANCE: FALSE
  PYANSYS_OFF_SCREEN: True

jobs:

  check_image:
    name: Validate latest mapdl image
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      mapdl:
        # Docker Hub image
        image: ghcr.io/pyansys/pymapdl/mapdl:latest
        ports:
          - 21000:50052
          - 21001:50055
        env:
          ANSYSLMD_LICENSE_FILE: 1055@${{ secrets.LICENSE_SERVER }}

        options: >-
          --restart always
          --health-cmd="ps aux | grep "[/]ansys_inc/.*grpc" -q  && test -f file.lock && echo 0 || echo 1"
          --health-interval=5s
          --health-retries=6
          --health-timeout=1s

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install OS packages
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-glx xvfb

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: Python-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements/requirements_tests.txt') }}
          restore-keys: |
            Python-${{ runner.os }}-${{ matrix.python-version }}

      - name: Install ansys-mapdl-core
        run: |
          python -m pip install --upgrade pip
          pip install .
          xvfb-run python -c "from ansys.mapdl import core as pymapdl; print(pymapdl.Report())"

      - name: Login in Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit Testing
        run: |
          pip install -r requirements/requirements_tests.txt
          cd tests
          xvfb-run pytest -v --cov=ansys.mapdl.core --cov-report=xml --cov-report=html

      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs-nightly'

      - name: Display files structure
        if: failure()
        run: |
          ls -R

      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs-nightly.tgz ./logs-nightly

      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs-nightly.tgz
          path: ./logs-nightly.tgz

      - name: Notify if fail
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ failure() }}
        with:
          webhook_url: ${{ secrets.TEAM_HOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{
            title: `Nightly MAPDL check (${workflow}) failed.`, 
            }"
